// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package layouts

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func MarketingSegment(child templ.Component) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"min-h-dvh flex flex-col\"><header class=\"border-b border-border bg-background/80 backdrop-blur sticky top-0 z-40\"><nav class=\"mx-auto flex max-w-6xl items-center justify-between px-4 py-3\"><a href=\"/\" class=\"flex items-center gap-2 font-semibold tracking-tight\"><span class=\"grid h-6 w-6 place-items-center rounded-md bg-foreground text-background text-xs\">S</span> Segment</a><div class=\"flex items-center gap-1 text-sm\"><a href=\"/\" class=\"px-3 py-1.5 rounded-md text-muted-foreground hover:text-foreground hover:bg-muted transition-colors\">Home</a> <a href=\"/about\" class=\"px-3 py-1.5 rounded-md text-muted-foreground hover:text-foreground hover:bg-muted transition-colors\">About</a> <a href=\"/login\" class=\"px-3 py-1.5 rounded-md bg-foreground text-background hover:opacity-90 transition-opacity\">Sign in</a></div></nav></header><main id=\"outlet-marketing\" class=\"flex-1\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = child.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</main><footer class=\"border-t border-border py-6\"><p class=\"mx-auto max-w-6xl px-4 text-sm text-muted-foreground\">© 2026</p></footer></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
