// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "net/http"

func Billing() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"mx-auto max-w-2xl space-y-8\"><div><h1 class=\"text-2xl font-bold tracking-tight\">Billing</h1><p class=\"mt-1 text-sm text-muted-foreground\">Manage your plan and invoices.</p></div><div class=\"rounded-lg border border-border bg-background p-5\"><div class=\"flex items-center justify-between\"><div><p class=\"text-sm font-medium\">Current plan</p><p class=\"text-sm text-muted-foreground\">—</p></div><span class=\"rounded-full border border-border px-3 py-1 text-xs font-medium\">—</span></div><div class=\"mt-4 border-t border-border pt-4\"><button type=\"button\" class=\"btn btn-outline\" hx-post=\"/billing/export\" hx-swap=\"none\">Export</button></div></div><div class=\"rounded-lg border border-border bg-background\"><div class=\"flex items-center justify-between border-b border-border px-5 py-3\"><p class=\"text-sm font-semibold\">Invoices</p></div><div class=\"divide-y divide-border text-sm\"><p class=\"px-5 py-4 text-muted-foreground\">No invoices yet.</p></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func billingLeaf(r *http.Request) (string, templ.Component) {
	return "Billing", Billing()
}

var BillingLeaf = billingLeaf

var _ = templruntime.GeneratedTemplate
