// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section class=\"mx-auto max-w-6xl px-4 py-20 md:py-28\"><div class=\"mx-auto max-w-2xl text-center\"><span class=\"inline-flex items-center rounded-full border border-border px-3 py-1 text-xs font-medium text-muted-foreground\">Template</span><h1 class=\"mt-6 text-4xl font-bold tracking-tight md:text-6xl\">Your project,<br>ready to build on.</h1><p class=\"mt-6 text-lg text-muted-foreground\">A starting point with auth, a Postgres-backed store, Redis sessions and caching, and server-rendered layouts.</p><div class=\"mt-10 flex items-center justify-center gap-3\"><a href=\"/login\" hx-get=\"/login\" hx-push-url=\"true\" class=\"btn btn-secondary\">Open the app</a> <a href=\"/about\" hx-get=\"/about\" hx-push-url=\"true\" class=\"btn btn-outline\">Learn more</a></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
